---
- name: Create HAProxy group
  ansible.builtin.group:
    name: "{{ haproxy_group }}"
    system: true
    state: present

- name: Create HAProxy user
  ansible.builtin.user:
    name: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    system: true
    state: present
    shell: /sbin/nologin
    home: "{{ haproxy_socket_dir }}"
    create_home: false

- name: Install runtime prerequisites on RHEL/CentOS/Rocky Linux
  ansible.builtin.package:
    name:
      - curl
      - python3
      - rsyslog
    state: present
  when:
    - ansible_facts['os_family'] == 'RedHat'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"

- name: Install runtime prerequisites on Debian/Ubuntu
  ansible.builtin.package:
    name:
      - curl
      - python3
      - rsyslog
    state: present
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Enable non-local binding for the VIP
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    sysctl_file: /etc/sysctl.d/60-keepalived.conf
    sysctl_set: true
    reload: true
    state: present
