---
haproxy_loadbalancer_master: "proxy-master"
haproxy_loadbalancer_backup: "proxy-backup"
haproxy_enabled: true
haproxy_install_method: package
haproxy_version: "3.4.0"
haproxy_stats: true
haproxy_stats_page_pass: "test_password_123456"
keepalived_enabled: true
keepalived_install_method: package
keepalived_version: "2.3.4"
keepalived_network_interface: eth0
keepalived_peer_group: proxy_hosts
keepalived_nopreempt: true
keepalived_advert_int: 2
keepalived_garp_master_delay: 5
keepalived_sync_groups:
  - name: SG_TEST
    instances:
      - VI_TEST
      - VI_TEST2
keepalived_vrrp_instances:
  - vrrp_instance_name: VI_TEST
    virtual_ipaddress: "172.18.0.100"
    virtual_router_id: 51
  - vrrp_instance_name: VI_TEST2
    virtual_ipaddress: "172.18.0.101"
    virtual_router_id: 52
keepalived_auth_type: PASS
keepalived_auth_pass: "vrrpsec"
haproxy_frontends:
  - name: test_http_frontend
    address: "*"
    port: 8080
    default_backend: test_backend
    mode: http
    acls:
      - "is_health path /healthz"
    use_backends:
      - backend: test_backend
        condition: "if is_health"
    http_request_rules:
      - "set-header X-Test 1"
    http_response_rules:
      - "set-header X-Frame-Options DENY"
haproxy_backends:
  - name: test_backend
    balance: roundrobin
    mode: http
    servers:
      - backend1
    port: 80
    options:
      - check
haproxy_global_extra: |
  tune.ssl.default-dh-param 2048
haproxy_custom_sections: |
  peers mypeers
    peer proxy-master 172.18.0.2:1024
haproxy_errorfiles:
  - code: 503
    path: /etc/haproxy/errors/503.http
haproxy_resolvers:
  - name: dns
    nameservers:
      - "ns1 127.0.0.1:53"
