---
- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted

- name: Restart haproxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted

- name: Restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
    enabled: true

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Reload systemd and enable floating IP service
  ansible.builtin.systemd_service:
    name: cloud-floating-ip
    daemon_reload: true
    enabled: true
    state: started

- name: Cleanup haproxy config backups
  ansible.builtin.shell: |
    set -o pipefail
    find {{ haproxy_config_dir }} -name 'haproxy.cfg.*' -printf '%T@ %p\0' |
      sort -zn | head -zn -2 | cut -zd' ' -f2- |
      xargs -0 rm -f
  args:
    executable: /bin/bash
  changed_when: false

- name: Cleanup keepalived config backups
  ansible.builtin.shell: |
    set -o pipefail
    find {{ keepalived_config_dir }} -name 'keepalived.conf.*' ! -name 'keepalived.conf.sample' -printf '%T@ %p\0' |
      sort -zn | head -zn -2 | cut -zd' ' -f2- |
      xargs -0 rm -f
  args:
    executable: /bin/bash
  changed_when: false
